name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@8921fa8a9af6c3b7c7d8ed2b2137527991681dec
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        website
