{{- $hasConfig := or .Values.config.content (not (empty .Values.secrets.keysJson)) .Values.secrets.keysJsonRaw -}}
{{- if and (not .Values.config.existingSecret) $hasConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "_.configSecretName" . }}
  labels:
    {{- include "_.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.content }}
  {{ .Values.config.configKey | default "config.hcl" }}: |
{{ .Values.config.content | nindent 4 }}
  {{- end }}
  {{- if or .Values.secrets.keysJsonRaw (not (empty .Values.secrets.keysJson)) }}
  {{ .Values.secrets.keysKey | default "keys.json" }}: |
    {{- if .Values.secrets.keysJsonRaw }}
{{ .Values.secrets.keysJsonRaw | nindent 4 }}
    {{- else }}
{{ .Values.secrets.keysJson | toJson | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
