name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@8921fa8a9af6c3b7c7d8ed2b2137527991681dec
    with:
      github-token: ${{ github.token }}
      plugins: |
        docker-compose=https://github.com/egose/asdf-docker-compose.git

  - name: Install python tools
    run: |
      pip install --require-hashes -r requirements.txt
      asdf reshim
    shell: bash
